### ISSUE TITLE
Warning messages when I run N1QLQueryExample

### ISSUE THREAD

**Issue by ogis-hashi** [couchbaselabs/couchbase-spark-samples#2]
When I ran the N1QLQueryExample.scala, the following warning occurs. 

``` text
2016-04-28 06:13:04 WARN  CouchbaseCore:166 - Exception while Handling Response Events null
java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
    at com.couchbase.client.deps.com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:45)
    at com.couchbase.client.deps.com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:55)
    at com.couchbase.client.deps.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:123)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at com.couchbase.client.deps.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
2016-04-28 06:13:04 WARN  CouchbaseCore:166 - Exception while Handling Request Events RequestEvent{request=null}
java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
    at com.couchbase.client.deps.com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:45)
    at com.couchbase.client.deps.com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:55)
    at com.couchbase.client.deps.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:123)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at com.couchbase.client.deps.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"
2016-04-28 06:13:04 WARN  CouchbaseCore:166 - Exception while Handling Response Events null
java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
    at com.couchbase.client.deps.com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:45)
    at com.couchbase.client.deps.com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:55)
    at com.couchbase.client.deps.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:123)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at com.couchbase.client.deps.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
2016-04-28 06:13:04 WARN  CouchbaseCore:166 - Exception while Handling Request Events RequestEvent{request=null}
java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
    at com.couchbase.client.deps.com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:45)
    at com.couchbase.client.deps.com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:55)
    at com.couchbase.client.deps.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:123)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at com.couchbase.client.deps.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
```

What is the reason and how to avoid the warning.

**Comment by daschl** [comment]
@tokomakoma123 can you please provide more insight into your environment? Which spark version, which server version, can you provide a code snippet that I can use to reproduce?

Thanks!

**Comment by ogis-hashi** [comment]
@daschl
The followings are build.sbt and N1QLExample.scala. I added _sc.stop_ and _exit_ to the original code.

```
name := "spark-examples"

version := "1.0"

//scalaVersion := "2.10.0"

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % "1.6.1" % "provided",
  "org.apache.spark" %% "spark-mllib" % "1.6.1",
  "org.apache.spark" % "spark-streaming_2.10" %  "1.6.1",
  "com.googlecode.json-simple" % "json-simple" % "1.1.1",
  "com.databricks" % "spark-csv_2.10" % "1.4.0",
  "org.scalacheck" %% "scalacheck" % "1.13.0" % "test",
  "org.scalatest" % "scalatest_2.10" % "2.0" % "test",
  "com.couchbase.client" %% "spark-connector" % "1.1.0"
  //"com.couchbase.client" % "java-client" % "2.2.5"
)
```

``` scala
import com.couchbase.client.java.query.N1qlQuery
import com.couchbase.spark._
import org.apache.spark.sql.SQLContext
import org.apache.spark.sql.sources.EqualTo
import org.apache.spark.{SparkConf, SparkContext}
import com.couchbase.spark.sql._

// sbt compile
// sbt "run-main newtech.N1QLExample"

object N1QLExample {

  def main(args: Array[String]): Unit = {

    // Configure Spark
    val cfg = new SparkConf()
      .setAppName("n1qlQueryExample")
      .setMaster("local[*]")
      .set("com.couchbase.bucket.travel-sample", "")

    // Generate The Context
    val sc = new SparkContext(cfg)

    // Spark SQL Setup
    val sql = new SQLContext(sc)

    // Plain old Spark emitting RDDs from a N1QL Query result
    sc.couchbaseQuery(N1qlQuery.simple("SELECT * from `travel-sample` LIMIT 10"))
      .collect()
      .foreach(println)

    // Create a DataFrame with Schema Inference
    val df = sql.read.couchbase(schemaFilter = EqualTo("type", "airline"))

    // A DataFrame can also be created from an explicit schema
    /*val df = sql.n1ql(StructType(
      StructField("name", StringType) ::
      StructField("abv", DoubleType) ::
      StructField("type", StringType) :: Nil
    ))*/

    // Print The Schema
    df.printSchema()

    // SparkSQL Integration
    df
      .select("name", "callsign")
      .sort(df("callsign").desc)
      .show(10)

    sc.stop
    exit
  }
}
```

Thanks !

**Comment by daschl** [comment]
@tokomakoma123 indeed, I saw the same thing when running it. I think this happens during shutdown.

I'll investigate - here is the ticket for it: https://issues.couchbase.com/browse/SPARKC-51 I'll close this one if thats okay so we can track it in one place - thanks for raising it!

**Comment by daschl** [comment]
Apparently this is expected: https://mail-archives.apache.org/mod_mbox/incubator-spark-user/201406.mbox/%3CCAMJOb8=6Q9xDhLALyo-bWQR3AkMz=ost=7jhTad7Zduv7mpQ0w@mail.gmail.com%3E but I'll add some code that will make sure we register a shutdown hook and cleanup.. but this error can be disregarded as well as out threads printing that

**Comment by daschl** [comment]
in 1.2.1 (unreleased) it goes away against local with 

CouchbaseConnection().stop()
sc.stop()

but in a worker setup I'm not so sure.. I'm still trying to find a way to do proper shutdown signalled by spark but currently I don't know how
